-- 1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employee WHERE SALARY > (SELECT SALARY FROM employee WHERE LAST_NAME='Bull');

-- 2
SELECT FIRST_NAME, FIRST_NAME FROM employee WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID FROM employee WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM departments WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM locations WHERE COUNTRY_ID='US'))); 

-- 3
SELECT FIRST_NAME, LAST_NAME FROM employee WHERE MANAGER_ID in (SELECT EMPLOYEE_ID FROM employee WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM departments WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM locations WHERE COUNTRY_ID='US')));

-- 4
SELECT FIRST_NAME, LAST_NAME FROM employee WHERE MANAGER_ID in (SELECT EMPLOYEE_ID FROM employee WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM departments WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM locations WHERE COUNTRY_ID='US')));

-- 5
SELECT FIRST_NAME, LAST_NAME, SALARY from employee where SALARY > (SELECT AVG(SALARY) from employee);

-- 6
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employee WHERE SALARY > (SELECT SALARY FROM employee WHERE LAST_NAME='Bull');

-- 7
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employee WHERE SALARY > (SELECT AVG(SALARY) FROM employee);

-- 8
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employee WHERE SALARY > (SELECT SALARY FROM employee WHERE LAST_NAME='Bull');

-- 9
SELECT * FROM employee WHERE SALARY = (SELECT MIN(SALARY) FROM employee);

-- 10
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employee WHERE SALARY > (SELECT AVG(SALARY) FROM employee);

-- 11
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY FROM employee WHERE SALARY > ALL (SELECT SALARY FROM employee WHERE JOB_ID = 'SH_CLERK');
