-- 1
SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM employee 
WHERE SALARY > (SELECT SALARY FROM employee WHERE LAST_NAME='Bull');

-- 2
SELECT FIRST_NAME, FIRST_NAME 
FROM employee 
WHERE DEPARTMENT_ID
IN (SELECT DEPARTMENT_ID FROM departments WHERE DEPARTMENT_NAME='IT'); 

-- 3
SELECT FIRST_NAME, LAST_NAME 
FROM employee 
WHERE MANAGER_ID 
IN (SELECT EMPLOYEE_ID FROM employee WHERE DEPARTMENT_ID 
IN (SELECT DEPARTMENT_ID FROM departments WHERE LOCATION_ID 
IN (SELECT LOCATION_ID FROM locations WHERE COUNTRY_ID='US')));

-- 4
SELECT FIRST_NAME, LAST_NAME 
FROM employee
WHERE (EMPLOYEE_ID IN (SELECT MANAGER_ID FROM employee));

-- 5
SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM employee
WHERE SALARY > (SELECT AVG(SALARY) FROM employee);

-- 6
SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM employee 
WHERE employee.SALARY = (SELECT MIN_SALARY 
FROM jobs 
WHERE employee.JOB_ID = jobs.JOB_ID);

-- 7
SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM employee
WHERE DEPARTMENT_ID IN 
( SELECT DEPARTMENT_ID
      FROM departments
      WHERE DEPARTMENT_NAME LIKE 'IT%' )
AND SALARY >
(SELECT avg(SALARY) FROM employee);

-- 8
SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM employee 
WHERE SALARY > (SELECT SALARY FROM employee WHERE LAST_NAME='Bull');

-- 9
SELECT * 
FROM employee 
WHERE SALARY = (SELECT MIN(SALARY) FROM employee);

-- 10
SELECT * FROM employee
WHERE SALARY > 
ALL(SELECT avg(SALARY)FROM employee GROUP BY DEPARTMENT_ID);

-- 11
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY 
FROM employee 
WHERE SALARY > ALL (SELECT SALARY FROM employee WHERE JOB_ID = 'SH_CLERK');

-- 12
SELECT b.FIRST_NAME, b.LAST_NAME 
FROM employee b 
WHERE NOT EXISTS (SELECT 'X' FROM employee a WHERE a.MANAGER_ID = b.EMPLOYEE_ID);

-- 13
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, 
(SELECT DEPARTMENT_NAME FROM departments d
 WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID) department 
 FROM employee e ORDER BY department;

-- 14
SELECT EMPLOYEE_ID, FIRST_NAME 
FROM employee AS A 
WHERE SALARY > 
(SELECT AVG(SALARY) FROM employee WHERE DEPARTMENT_ID = A.DEPARTMENT_ID);

SELECT AVG(SALARY) FROM employee WHERE DEPARTMENT_ID IN (10, 20, 30, 50, 90, 100);


